#! /bin/sh
### BEGIN INIT INFO
# Provides: 		tempMonitorService
# Required-Start:	$all
# Required-Stop:	
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Start the temperature monitoring system
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin

. /lib/init/vars.sh

case "$1" in
	start)
		log_begin_msg "Starting temperature monitoring service"
		log_end_msg $?
		exit 0
		;;
	stop)
		log_begin_msg "Stopping temperature monitoring service"
		log_end_msg $?
		exit 0
		;;
	*)
		echo "Usage: /etc/init.d/tempMonitorService {start|stop}"
		exit 1
		;;
esac
